In [2]:
import numpy as np

In [10]:
array=np.array([[1,2,3,4,],[5,6,7,8]],ndmin=50)
print(array)

[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1
                                                  2
                                                  3
                                                  4]
                                                 [5
                                                  6
                                                  7
                                                  8]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]


In [11]:
array=np.array([[1,2,3,4,],[5,6,7,8]])
print(array)
print(array.ndim) #2dmin

[[1 2 3 4]
 [5 6 7 8]]
2


In [12]:
array=np.array([[[1,2,3,4,],[5,6,7,8],[1,3,6,8]]])
print(array)
print(array.ndim)  #3

[[[1 2 3 4]
  [5 6 7 8]
  [1 3 6 8]]]
3


In [13]:
import numpy as np
import pandas as pd
import array as arr

In [14]:
data={'salary':[4000,5000,None,8000]}
df=pd.DataFrame(data)
sal=df["salary"].mean()
df['salary']=df['salary'].fillna(df['salary'].mean())
print(df['salary'])

0    4000.000000
1    5000.000000
2    5666.666667
3    8000.000000
Name: salary, dtype: float64
